name = "fertility-benefits-toolkit"
compatibility_date = "2024-01-01"

[env.production]
name = "fertility-benefits-toolkit"
route = { pattern = "fertility-benefits-toolkit.pages.dev", zone_name = "pages.dev" }

# Pages configuration
[build]
command = "npm run build"
destination = "dist"

# Environment variables (if needed)
# [vars]
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

# Custom headers for SPA routing
[[headers]]
for = "/*"
[headers.values]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"Referrer-Policy" = "strict-origin-when-cross-origin"

# SPA fallback for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200